### ISSUE TITLE
Query Highlighting

### ISSUE THREAD

**Issue by Gerst20051** [jobedom/sublime-php-modern#12]
Do you know how to make this quys example mysql highlight correctly when it starts on the next line?

http://superuser.com/questions/355766/how-do-i-get-sublime-text-2-to-properly-color-sql-even-if-its-inside-a-php-strin

**Comment by jobedom** [comment]
As far as I know, syntax higlighting for PHP in Sublime Text doesn't use SQL highlighting for SQL inside strings. It does, however, highlight SQL if inside a heredoc block marked with "SQL". Like this:

```php
$q = <<<SQL
SELECT * FROM users WHERE active;
SQL;
```
I don't know if trying to detect SQL inside regular strings makes sense. What do you think?

**Comment by Gerst20051** [comment]
@jobedom it does highlight sql inside strings. for example

```
// Works
$qry = "SELECT * FROM users WHERE deleted = 0;"
```
```
// Works
$qry = "SELECT
        *
    FROM users
    WHERE deleted = 0;"
```
```
// Works
$qry = "                     SELECT * FROM users WHERE deleted = 0;"
```
```
// Works
$qry = "                     SELECT
        *
    FROM users
    WHERE deleted = 0;"
```
```
// Doesn't Work
$qry = "
    SELECT * FROM users WHERE deleted = 0;"
```

**Comment by Gerst20051** [comment]
![screenshot 2015-01-21 22 05 02](https://cloud.githubusercontent.com/assets/235372/5849831/06e4ba8c-a1b9-11e4-8694-f6c3e96994e3.png)

**Comment by jobedom** [comment]
Thanks, Gerst! I use a very minimalistic theme so I didn't noticed the highlighting myself. I'm checking the problem with newlines at the begining of the string.

**Comment by Gerst20051** [comment]
@jobedom thanks i look forward to learning what you find out!!

**Comment by jobedom** [comment]
Fixing this in the official standar Sublime PHP package, as I'm moving development into it now. Please uninstall this package and stay tuned!

**Comment by jobedom** [comment]
It's fixed in official PHP package now. Waiting for the PR to be accepted. Thanks, Gerst20051

**Comment by Gerst20051** [comment]
@jobedom awesome news! do you have a link to the merge request?

**Comment by jobedom** [comment]
https://github.com/sublimehq/Packages/pull/22
