### ISSUE TITLE
Not work with Build 3084

### ISSUE THREAD

**Issue by 23r9i0** [jobedom/sublime-php-modern#14]
In older versions of sublime worked perfectly, but on Build 3024 sublime select of default packages PHP and not select PHP 5.
I can manually select PHP 5 but not permanently.

Any Solution?

**Comment by jobedom** [comment]
I have the same problem. I'm on it.

**Comment by jobedom** [comment]
I decided to move development to standard Sublime PHP package now. I suggest you uninstall this package and just use the official one. I'll be sending PRs with all the enhancements.
