### ISSUE TITLE
Multiline function parameters not highlighting properly

### ISSUE THREAD

**Issue by rtheunissen** [jobedom/sublime-php-modern#15]
![screen shot 2015-06-07 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/809191/8022178/d07525a0-0d14-11e5-8240-d3f54fa46f9a.png)

**Comment by jobedom** [comment]
I'm moving development onto the standard official PHP package now. Using it, both arguments have context `meta.function.arguments.php`. 

I'll be sending PRs with all the enhancements PHP Modern has and the standard package hasn't.
