### ISSUE TITLE
Typehinted array argument with a default value is broken

### ISSUE THREAD

**Issue by rtheunissen** [jobedom/sublime-php-modern#16]
![screen shot 2015-06-07 at 12 57 26 pm](https://cloud.githubusercontent.com/assets/809191/8022181/e799f03a-0d14-11e5-9c08-e2126fd5a43a.png)

**Comment by jobedom** [comment]
That's correct. Type hinted parameters can only have a default value if it's `null`. Otherwise it will generate a fatal error.

**Comment by rtheunissen** [comment]
Are you saying that you can only use `null` default values for function parameters? That is incorrect.

**Comment by jobedom** [comment]
You're right. Once again, [PHP documentation](http://php.net/manual/en/language.oop5.typehinting.php) is misleading. I tried this:

```php
<?php

function test1(array $data = null) {
   var_dump($data);
}

test1();
test1(null);
test1([1, 2, 3]);

// Result:

// NULL
// NULL
// array(3) {
//   [0] =>
//   int(1)
//   [1] =>
//   int(2)
//   [2] =>
//   int(3)
// }


function test2(array $data = ['a', 'b', 'c']) {
   var_dump($data);
}

test2();
test2([1, 2, 3]);
test2(null);

// Result:

// array(3) {
//   [0] =>
//   string(1) "a"
//   [1] =>
//   string(1) "b"
//   [2] =>
//   string(1) "c"
// }
// array(3) {
//   [0] =>
//   int(1)
//   [1] =>
//   int(2)
//   [2] =>
//   int(3)
// }
// PHP Catchable fatal error:  Argument 1 passed to test2()
// must be of the type array, null given
```
It happens you cannot pass a `null` if the default value is not a `null` itself. And that's it.

Not only Sublime Text packages (mine included) get this wrong. Even GitHub Markdown syntax highlighter interprets it wrong, as you can see. The prose in the PHP manual is atrocious.

I'll look into it in my own branch of the standard PHP package.

Thanks a lot.

**Comment by rtheunissen** [comment]
If you use `array()` it's fine. Short array syntax came with PHP 5.4, and my guess is that many syntax highlighting rules weren't updated accordingly.

```php

function a(array $a = array(1, 2, 3)) {

}

function a(array $a = [1, 2, 3]) {

}
```

**Comment by jobedom** [comment]
Oh, I see. I'll fix that. Thanks.
