### ISSUE TITLE
Merge into Default Packages

### ISSUE THREAD

**Issue by jbrooksuk** [jobedom/sublime-php-modern#17]
Sublime Text has open sourced the default packages. How would you feel about pushing your changes to it?

https://github.com/sublimehq/Packages/tree/master/PHP

**Comment by jobedom** [comment]
I'll take a look. It would be great to have a standard modern PHP package. Thanks a lot.

**Comment by jobedom** [comment]
I'm doing that. Thanks for the suggestion.

**Comment by jbrooksuk** [comment]
You're awesome! :D
