### ISSUE TITLE
high cpu load

### ISSUE THREAD

**Issue by pcr-coding** [jobedom/sublime-php-modern#2]
If php modern is activated I get 3 more sublime tasks in task manager with a load of 20% each task. I think this is not a normal behavior.
If I deactivate it, everything is normal again.

SLT 3 Build 3059
Windows 8.1

**Comment by sebastiaandegeus** [comment]
It's completely unusable. My whole mac slows down to a complete stop.

**Comment by rezen** [comment]
Same here, on Win7x64 Build 3083.

**Comment by jobedom** [comment]
I've deprecated this package and moved any improvement into the official PHP package. I hope they accept my PR requests!
