### ISSUE TITLE
llamada a metodo en clase, error de definicion

### ISSUE THREAD

**Issue by 23r9i0** [jobedom/sublime-php-modern#4]
hola,
el plugin considera la llamada a un metodo como una variable.other.property.php en vez de meta.function-call.object.php
```php
ClassName->method( $args );
```
Lo podrias mirar? 
Saludos

**Comment by jobedom** [comment]
Acabo de cerrar el desarrollo del plugin ahora que los paquetes estandar de Sublime son de código abierto. Enviaré PRs con todas las funcionalidades que tiene PHP Modern para que las integren en el paquete oficial PHP. 

En dicho paquete oficial, el problema que me comentas no existe.

Saludos.
