### ISSUE TITLE
`use` statements with multiple items doesn't highlight properly.

### ISSUE THREAD

**Issue by donut** [jobedom/sublime-php-modern#8]
If I separate multiple items in a `use` statement with a comma, only the first item is properly highlighted:

![example](https://www.dropbox.com/s/eb5x9ic94hvnvu1/Screenshot%202014-09-16%2014.14.56.png?dl=1)

**Comment by jbrooksuk** [comment]
:+1:

I say we update `PHP.tmLangauge` to the [latest version](https://github.com/textmate/php.tmbundle/blob/master/Syntaxes/PHP.plist) by Textmate, since it seems to be doing everything.

**Comment by jobedom** [comment]
It's working properly using standard PHP official package.
